pathgl.fragment = [ "precision mediump float;"
                  , "uniform vec4 rgb;"
                  , "uniform float time;"
                  , "uniform vec2 resolution;"
                  , "void main(void) {"
                  , "  gl_FragColor = rgb;"
                  , "}"
                  ].join('\n')

pathgl.vertex = [ "attribute vec3 aVertexPosition;"
                , "uniform mat4 uPMatrix;"
                , "uniform vec3 xyz;"
                , "uniform vec2 rotation;"
                , "void main(void) {"
                , "vec3 rotatedPosition = vec3(aVertexPosition.x * rotation.y + aVertexPosition.y * rotation.y, "
                                            + "aVertexPosition.y * rotation.y + aVertexPosition.x * rotation.x,"
                                            + "aVertexPosition.z);"
                , "  gl_Position = uPMatrix * vec4(xyz + rotatedPosition, 1.0);"
                , "}"
                ].join('\n')
